[project]
name = "vehicule_detection"
version = "0.1.0"
description = "Small project for vehicule_detection using computer vision"
module = "vehicule_detection"

[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]
