name: Build Docker Container and Test Python Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code source
    - name: Checkout repository
      uses: actions/checkout@v2

    # Étape 2 : Construire l'image Docker
    - name: Build Docker container
      run: |
        docker build -t python-app .

    # Étape 3 : Exécuter les tests à l'intérieur du conteneur
    - name: Run tests inside Docker container
      run: |
        docker run --rm python-app python -m unittest discover -s ./tests
